version: '3'
services:
  myapp:
    image: openjdk:11-jre-slim
    volumes:
      - /Users/purvashapadhy/DevOps-753/my-app/target:/app
    working_dir: /app
    command: java -jar my-app-1.0-SNAPSHOT.jar
