version: '3'
services:
  myapp:
    image: openjdk:11
    container_name: myapp
    volumes:
      - ./target/my-app-1.0-SNAPSHOT.jar:/my-app.jar
    command: ["java", "-jar", "/my-app.jar"]
    ports:
      - "8080:8080"
